name: bubbly
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.3.7'

dependencies:
  flutter:
    sdk: flutter

  bubbly_camera:
    path: "CameraPlugin/camera"

  app_tracking_transparency: ^2.0.3
  google_mobile_ads: ^2.3.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  shared_preferences: ^2.0.5
  marquee: ^2.0.0
  detectable_text_field: ^2.1.0
  webview_flutter: ^3.0.4
  bouncing_widget: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_branch_sdk: ^5.1.0
  share_plus: ^4.0.4
  audioplayers: ^5.2.1
  audioplayers_darwin: ^5.0.2
  video_player: ^2.7.2
  device_info_plus: ^8.1.0
  visibility_detector: ^0.3.3

  image_gallery_saver: ^2.0.3
  get: ^4.6.6
  flutter_staggered_grid_view: ^0.7.0



  #  FireBase
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.7.2

  sign_in_with_apple: ^5.0.0
  google_sign_in: ^5.0.1
  http: ^0.13.1
  shimmer: ^2.0.0
  image_picker: ^0.8.5+3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  file_picker: ^5.2.5
  flutter_downloader: ^1.11.6
  ffmpeg_kit_flutter_full: ^4.5.1
  path_provider: ^2.0.1
  url_launcher: ^6.0.4
  flutter_local_notifications: ^14.0.0+1
  flutter_video_info:
  permission_handler: ^10.2.0
  intl: ^0.18.0
  collection: ^1.16.0
  video_thumbnail:
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  path: ^1.8.3

  #----------------- Live Stream -----------------#
  agora_rtc_engine: ^6.2.4

  #----------------- MVVM -----------------#
  stacked: ^3.2.5
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - icons/

  fonts:
    - family: SfUiBold
      fonts:
        - asset: font/SFUIDisplayBold.otf
    - family: SfUiLight
      fonts:
        - asset: font/SFUIDisplayLight.otf
    - family: SfUiMedium
      fonts:
        - asset: font/SFUIDisplayMedium.otf
    - family: SfUiHeavy
      fonts:
        - asset: font/SFUIDisplayHeavy.otf
    - family: SfUiRegular
      fonts:
        - asset: font/SFUIDisplayRegular.otf
    - family: SfUiSemiBold
      fonts:
        - asset: font/SFUIDisplaySemibold.otf

